name: RL Scan with gh-action-rl-scanner-composite

on:
  # The "gh-action-rl-scanner-composite" action only works with push and pull_request triggers
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REPORT_DIR: "RLreport"

jobs:
  Build-And-Scan:
    runs-on: ubuntu-latest
    
    permissions:
      statuses: write
      pull-requests: write
      # The next 3 permissions are used for SARIF report upload
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Check out
        uses: actions/checkout@v3.5.3

      - name: Set Current Date Time
        run: |
          echo "DT_NOW=$(date +%Y%m%d-%H%M%S)" >> ${GITHUB_ENV}
          
      - name: Set up Java
        uses: actions/setup-java@v3.11.0
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'maven'

      - name: Build
        run: |
          mvn -B clean package
          
      - name: RL scan
        continue-on-error: true # Remove this line if you want the overall run to fail when the scan detects policy violations
        id: rl-scan

        env:
          RLSECURE_ENCODED_LICENSE: ${{ secrets.RLSECURE_ENCODED_LICENSE }}
          RLSECURE_SITE_KEY: ${{ secrets.RLSECURE_SITE_KEY }}

        uses: reversinglabs/gh-action-rl-scanner-composite@v1.0.0
        with:
          artifact-to-scan: 'target/struts2-showcase.war'
          report-path: ${{ env.REPORT_DIR }}
